### ISSUE TITLE
Install not working correctly

### ISSUE THREAD

**Issue by camjac251** [zewt/zDsonImport#1]
Hey there

I wanted to let you know that the install.bat doesn't work properly for me. I ended up having to fix it manually afterward.

It creates this mod file
```
+ zMayaTools 1.0 C:\Windows\system32 
MAYA_CUSTOM_TEMPLATE_PATH +:= scripts/NETemplates 

``` 
but the path is incorrect, this was also with the folder installed on my Desktop, then in the C root. I ended up correcting the path to my correct path and moved the .mod files to %USERPROFILE%\Documents\maya\2018\modules

**Comment by camjac251** [comment]
I also am getting a few other errors as well

```
// pymel.core : Updating pymel with pre-loaded plugins: svgFileTranslator, invertShape, mayaHIK, GamePipeline, curveWarp, CloudImportExport, tiffFloatReader, MASH, poseInterpolator, bifrostvisplugin, ATFPlugin, hairPhysicalShader, ikSpringSolver, ik2Bsolver, xgenToolkit, AbcExport, retargeterNodes, gameFbxExporter, VectorRender, OpenEXRLoader, lookdevKit, Unfold3D, Type, mayaCharacterization, mtoa, meshReorder, modelingToolkit, MayaMuscle, rotateHelper, matrixNodes, bifmeshio, AbcImport, autoLoader, deformerEvaluator, sceneAssembly, gpuCache, Substance, OneClick, shaderFXPlugin, objExport, bifrostshellnode, renderSetup, GPUBuiltInDeformer, ArubaTessellator, quatNodes, fbxmaya
// Error: file: C:/Program Files/Autodesk/Maya2018/scripts/others/pluginWin.mel line 290: TypeError: file C:/zMayaTools-master/plug-ins/zFileSwitch.py line 115: unsupported operand type(s) for +: 'int' and 'str' // 
// Warning: file: C:/Program Files/Autodesk/Maya2018/scripts/others/pluginWin.mel line 290: Failed to call script initialize function // 
// Error: file: C:/Program Files/Autodesk/Maya2018/scripts/others/pluginWin.mel line 290:  (zFileSwitch) // 
# DSONImporter : Refreshing asset cache...
# Error: IOError: file C:\zDsonImport-master\scripts\dsonimport\dson\content.py line 242: 2 # 
```

This is on Maya 2018.3 (SP3)

**Comment by camjac251** [comment]
Also noticing that if the system unit is anything but cm then the script will not scale correctly.

**Comment by zewt** [comment]
That looks like the install batch file isn't running with its cwd set to the directory the file is in, which is odd.  What version of Windows are you on?

The script installs the .mod file into maya\modules rather than maya\version\modules, since that directory is searched by all versions so you don't have to reinstall modules when you upgrade Maya, but of course putting it in the version directory will work too.

I pushed a fix to zMayaTools to fix the zFileSwitch error.

**Comment by camjac251** [comment]
I'm running Windows 10 Pro Version 1709

**Comment by zewt** [comment]
The .bat file points the module at the current directory, and batch files are normally executed from the directory they're in, but it looks like it was executed from the system directory instead.  Did you execute it from Explorer or in some other way?

**Comment by zewt** [comment]
I'll reopen if you can give more info, but I can't repro this and don't know how it could have been executed to cause it.

**Comment by impactcolor** [comment]
I'm getting something similar but I can't run bat file cause I'm on a mac.  Is there any work around?
zOBBTransform.py line 7: No module named zMayaTools.obb_transform //

**Comment by zewt** [comment]
You need to create module files for zMayaTools and zDsonImport, to tell Maya about them.  You can use the attached ones (unzip it, GitHub won't let me attach it normally).  You'll need to edit the path on the first line of each to point to the correct directories.
[modules.zip](https://github.com/zewt/zDsonImport/files/2356125/modules.zip)

I don't know where Maya's module files live on OSX, you'll need to search around to find it.

One issue you'll run into is that it automatically locates your Daz3d library to find your assets, but it only knows how to do that on Windows.  I don't have a Mac to implement this, but if anyone wants to have a go at implementing this for OSX, the related code is here: https://github.com/zewt/zDsonImport/blob/master/scripts/dsonimport/dson/DSON.py#L1137
